version: "3"

networks:
  n1:
    external:
      name: data-center

services:
  mongo:
    hostname: mongo
    networks:
      - data-center
    image: mongo:4.2.23
    restart: unless-stopped
    container_name: mongo
    expose:
      - 27017
  
  car-api:
    hostname: car-api
    networks:
      - data-center
    env_file:
     - ./config.env
    build:
      context: .
      dockerfle: Dockerfile
    image: cognigy/car-api:1.0
    restart: unless-stopped
    container_name: car-api
    expose:
      - 5000
    ports:
      - "0.0.0.0:5000:5000"
